Add StringViewArray and BinaryViewArray (#4253)
apache/arrow-rs pull request #4585
Opened 2023-07-29 21:07 UTC by tustvold

_Draft as not yet standardised and needs a LOT more testing_
# Which issue does this PR close?

Closes #.

# Rationale for this change
 

# What changes are included in this PR?

# Are there any user-facing changes?

2023-07-30 10:06 UTC, alamb commented
Related mailing list discussion: https://lists.apache.org/thread/w88tpz76ox8h3rxkjl4so6rg3f1rv7wt

2023-07-30 10:09 UTC, alamb commented on arrow-data/src/view.rs
> +/// The element layout of a view buffer
The "small string optimization" in rust !!! -- I had wondered what this would look like

2023-09-06 18:08 UTC, bkietz requested changes
This looks good to me, I have just a few suggestions

2023-09-06 18:08 UTC, bkietz commented on arrow-data/src/equal/binary_view.rs
> +    true
For equality comparison, we can compare the length and prefix of the views simultaneously:
```suggestion
    let lhs_b = lhs.buffers()[1..];
    let rhs_views = &rhs.buffer::<u128>(0)[rhs_start..rhs_start + len];
    let rhs_b = rhs.buffers()[1..];

    for (idx, (l, r)) in lhs_views.iter().zip(rhs_views).enumerate() {
        // Only checking one null mask here because by the time the control flow reaches
        // this point, the equality of the two masks would have already been verified.
        if lhs.is_null(idx) {
            continue;
        }

        let l_len_prefix = *l as u64;
        let r_len_prefix = *r as u64;
        if l_len_prefix != r_len_prefix {
            return false;
        }

        let len = *l as u32;
        if len <= 12 {
            if (*l >> 64) as u64 != (*r >> 64) as u64 {
                return false;
            }
            continue;
        }

        let l_view = View::from(*l);
        let r_view = View::from(*r);

        let l_b = &lhs_b[l_view.buffer_index as usize];
        let r_b = &rhs_b[r_view.buffer_index as usize];

        // prefixes are already known to be equal; skip checking them
        let len = len as usize - 4;
        let l_o = l_view.offset as usize + 4;
        let r_o = r_view.offset as usize + 4;

        if l_b[l_o..l_o + len] != r_b[r_o..r_o + len] {
            return false;
        }
    }
    true
```

2023-09-06 18:24 UTC, tustvold commented on arrow-array/src/array/byte_view_array.rs
> +    views: ScalarBuffer<u128>,
On x86 this carries a 64-bit alignment, on some platforms it may have a higher alignment. The various APIs are already setup to handle this because of i128 based types such as intervals.

2023-09-06 18:26 UTC, tustvold commented on arrow-data/src/equal/binary_view.rs
> +    true
I'd have hoped LLVM is smart enough to work this out but I can double-check

2023-09-06 20:06 UTC, bkietz commented on arrow-array/src/array/byte_view_array.rs
> +    views: ScalarBuffer<u128>,
Well then, should there be a comment or `assert_ne!(std::mem::min_align_of::<u128>(), 128/8)`?

2023-09-06 20:09 UTC, tustvold commented on arrow-array/src/array/byte_view_array.rs
> +    views: ScalarBuffer<u128>,
I suppose we could add it, although I do wonder if we would be better off not mandating alignment in the standard at all and letting implementations adjust as necessary...

2023-09-07 00:51 UTC, bkietz commented on arrow-array/src/array/byte_view_array.rs
> +    views: ScalarBuffer<u128>,
I'm specifically worried that some implementations will come to depend on 128 bit alignment (and therefore be sporadically unable to consume arrays from other implementations which don't uphold that assumption) and on the other side that some implementations may produce views with as little as 32 bit alignment (and therefore produce arrays which are sporadically unacceptable to other implementations). Specific alignment is necessary for efficient and consistent consumption, so I feel it should be specified

2023-09-07 04:22 UTC, tustvold commented on arrow-array/src/array/byte_view_array.rs
> +    views: ScalarBuffer<u128>,
> therefore be sporadically unable to consume arrays from other implementations which don't uphold that assumption

This imo is a separate concern, arrow implementations should have fallback logic to ensure they can handle consuming misaligned buffers. This is because not all implementations, including arrow-cpp, guarantee them consistently - https://github.com/apache/arrow/issues/32276 https://github.com/apache/arrow/issues/36400

2023-09-07 12:52 UTC, bkietz commented on arrow-array/src/array/byte_view_array.rs
> +    views: ScalarBuffer<u128>,
That makes sense. Would you still object if [the alignment note in Columnar.rst](https://github.com/apache/arrow/pull/37526#discussion_r1317778621) were rewritten as a *recommendation*, as with the [Buffer Alignment and Padding section](https://github.com/apache/arrow/blob/b5d36e9f4d323f274e06ed04285ddd4e2121ab19/docs/source/format/Columnar.rst?plain=1#L137-L146)?

2023-09-07 13:37 UTC, tustvold commented on arrow-array/src/array/byte_view_array.rs
> +    views: ScalarBuffer<u128>,
Is the existing linked recommendation insufficient in this respect?

2023-09-07 16:07 UTC, bkietz commented on arrow-array/src/array/byte_view_array.rs
> +    views: ScalarBuffer<u128>,
I would say so, since it doesn't explain the advantage specific to string views.

2023-09-12 15:46 UTC, bkietz commented on arrow-array/src/array/byte_view_array.rs
> +    views: ScalarBuffer<u128>,
I have removed the alignment note in https://github.com/apache/arrow/pull/37526/commits/430b63098bbf770393ea2689cfa6bde750ed0852

2024-02-12 21:26 UTC, alamb commented
See https://github.com/apache/arrow-rs/issues/5374 for implementation discussions

2024-02-18 01:30 UTC, doki23 commented on arrow-array/src/array/byte_view_array.rs
> +        assert!(i < self.views.len());
This assertion is duplicate with the previous one.

2024-02-22 03:28 UTC, sundy-li commented on arrow-data/src/equal/binary_view.rs
> +            let r_view = View::from(*r);
We can compare the prefix to short-circuit.

As described in paper:

```
 In case of long strings, the remaining four bytes
of the header are used to store the first four characters of the string,
allowing Umbra to short-circuit some comparisons
```

2024-02-22 03:29 UTC, sundy-li commented on arrow-data/src/equal/binary_view.rs
> +            let r_view = View::from(*r);
Oh, I just note it's commend already. ignore this.

2024-02-22 03:31 UTC, sundy-li commented on arrow-data/src/view.rs
> +pub struct View {
do we need to use `#[repr(C)]` ?

2024-02-27 06:53 UTC, sundy-li commented
> Thanks for the comments @sundy-li . Is there any chance you or someone at DataBend are interested in / planning on working on this feature?

Yes, we are working on it at https://github.com/datafuselabs/databend/pull/14662 

In databend, our memory array is still based on arrow2. But reading/writing is using arrow-rs, we are planing to work on it after  https://github.com/datafuselabs/databend/pull/14662 is finished.

 @ariesdevil

2024-02-27 06:57 UTC, ariesdevil commented
Hi @alamb, I'm willing to work on this feature after https://github.com/datafuselabs/databend/pull/14662 is finished.

2024-02-28 11:22 UTC, alamb commented
> Hi @alamb, I'm willing to work on this feature after [datafuselabs/databend#14662](https://github.com/datafuselabs/databend/pull/14662) is finished.

Thank you @sundy-li  and @ariesdevil 

I left a comment on https://github.com/apache/arrow-rs/issues/5374 https://github.com/apache/arrow-rs/issues/5374#issuecomment-1968772760 about how we can potentially work on this together

2024-03-06 03:26 UTC, tustvold commented
I'm going to close this PR as I believe others are picking this up

2024-03-06 03:26 UTC, closed without merging

2024-03-06 07:56 UTC, alamb commented
> Add `StringViewArray` implementation and layout and basic construction + tests #5469

Indeed -- we are tracking the work in https://github.com/apache/arrow-rs/issues/5374