feat(object_store): publicly expose client error
apache/arrow-rs pull request #6158
Opened 2024-07-30 17:31 UTC by kyle-mccarthy

# Which issue does this PR close?

Closes #5345.

# Rationale for this change
 
Exposing the client error publicly allows accessing the status code of the response associated with the error. This gives the user more control over error handling, such as special handling for authn/authz errors.

```
let err = store.head(&path).await.unwrap_err();
let source = err
    .source()
    .unwrap()
    .downcast_ref::<object_store::ClientError>().unwrap();
let status = source.status().unwrap();
```

# What changes are included in this PR?

expose `client::Error as ClientError`

# Are there any user-facing changes?

Yes

# Notes

- Should the error type or its variants be renamed?
- Alternatively, a `PermissionDenied` variant could be added to `crate::Error`.
- Alternatively, `source` could be changed to `reqwest::Error` when the client error is converted to `crate::Error`. (Would allow downcasting directly to reqwest::Error.)

2024-07-30 19:45 UTC, alamb reviewed
Thanks @kyle-mccarthy  🙏 

It seems like that since the errors are now public the CI demands some of the methods be documented: https://github.com/apache/arrow-rs/actions/runs/10167031274/job/28118484246?pr=6158

2024-07-30 19:51 UTC, kyle-mccarthy commented
@alamb I noticed that the main error variant suppresses this warning via `#[allow(missing_docs)]`, is that acceptable here too?

Also, [I have a branch](https://github.com/kyle-mccarthy/arrow-rs/commit/193b159fec8e778769bb26f029e11ef4df561415) that adds a `PermissionDenied` variant, like the original ticket discussed. Let me know if this approach is preferable and I can repoint this PR.

2024-07-30 20:29 UTC, alamb commented
> @alamb I noticed that the main error variant suppresses this warning via `#[allow(missing_docs)]`, is that acceptable here too?

Is there a reason not to document them? For example would they add no value over the names of the variants themselves?


In my simple mind more documentation is always better than less (though I realize not everyone agrees with this assesment).

2024-07-30 22:10 UTC, kyle-mccarthy commented
@alamb Not at all, I added comments to the error enum! 

Note that I restricted the visibility of the `error()` method to the crate, I couldn't think of a valid reason to expose it publicly. Also, I had to conditionally compile it to resolve a failing check due to dead code.

2024-07-31 20:22 UTC, tustvold commented on object_store/src/client/retry.rs
> +    /// The response sent by the cloud provider was a redirect without a
If we do this I think we should make the variants opaque, and expose information with accessors. Otherwise it is going to be very hard to evolve this without introducing breaking changes

2024-07-31 20:23 UTC, tustvold commented
I'm rather apprehensive about this as it exposes a fair bit of internal implementation details. I personally would prefer a more targeted approach that exposes the error information you are looking to expose, as I stated on the original ticket

2024-07-31 20:44 UTC, alamb reviewed
cc @crepererum and @thinkharderdev  for your thoughts

2024-07-31 20:44 UTC, alamb commented on object_store/src/client/retry.rs
> +    /// The response sent by the cloud provider was a redirect without a
I think keeping the underlying error opaque is pretty hard to use and clearly there appears to be a need to get finer grained information about what the error was 

>Otherwise it is going to be very hard to evolve this without introducing breaking changes

Perhaps another possibility is to mark it as `[#non_exhaustive]` https://doc.rust-lang.org/reference/attributes/type_system.html

> If we do this I think we should make the variants opaque, and expose information with accessors. 

Are you suggesting something like 

```rust
impl Error {
  fn is_redirect(&self) -> bool {..}
  fn status_code(&self) -> Option<StatusCode> {..}
...
}
```

2024-07-31 20:45 UTC, alamb commented
If someone has time to design a better error abstraction for the client I would be happy to try and review it. However, I  don't think I would likely have the time do to so however

2024-07-31 21:17 UTC, tustvold commented on object_store/src/client/retry.rs
> +    /// The response sent by the cloud provider was a redirect without a
> Are you suggesting something like

Yes, this is also what the underlying HTTP clients do as well. My aprehension is we're exposing a fair amount of internal details around how we perform requests, retries, etc... that seems undesirable.

non-exhaustive would help for adding new variants, but we'd be unable to change existing. If say we wanted to add more context to a retry error message, this would be a breaking change

2024-07-31 21:22 UTC, tustvold commented
My personal feeling is the better abstraction is to add a permission denied variant to the top-level error. The problem is for historical reasons this wasn't marked non-exhaustive.

So either we defer this to the next breaking release, or we do something in the middleground to expose this variant in a non-breaking fashion. 

One option could simply be to add an opaque PermissionError that the generic error can be downcast to.

It all really depends on what the use-case is and how acute the need is

2024-07-31 21:23 UTC, kyle-mccarthy commented
@tustvold I understand your concerns and feel like they are valid. I [have a branch](https://github.com/kyle-mccarthy/arrow-rs/commit/25de698dd4765d6233002ce003fb710a5a959541) that takes an alternative approach and surfaces permissions problem though a `PermissionDenied` variant on the top level `object_store::Error` enum.

I am primarily wanting to be able able to identify permission related problems, so either direction would help me.

However, I think the core problem would still exist if just the `PermissionDenied` varient was added. The core problem being that `object_store` uses private types (albeit type erased) in the public `source` field of `object_store::Error::Generic` variant. This forces downstream users of the crate to handle all generic errors the same way, or resort to parsing the stringified error message.

2024-07-31 21:34 UTC, tustvold commented
> This forces downstream users of the crate to handle all generic errors the same way, or resort to parsing the stringified error message.

Right, the alternative being we expose public types and those types then become part of the public API, but in a somewhat obfuscated manner. This gets particularly spicy if one exposes foreign types, which we probably do in some places, then not only are these crates part of your public API but if those crate's make a breaking release any error handling code will happily build against a different version, and just silently not work :smile: 

The approach as it stands is to have explicit semantic error categories, this gives a lot of freedom to make breaking changes, and has a lot of precedent in the ecosystem (e.g. hyper, reqwest) and the standard library (std::io::Error), but does have downsides.

2024-08-01 08:58 UTC, crepererum requested changes
This PR kinda sidesteps / ignores the discussion in #5345 that -- more or less -- concluded that we do NOT want to expose too many implementation details.

2024-08-01 11:03 UTC, alamb commented
> This PR kinda sidesteps / ignores the discussion in #5345 that -- more or less -- concluded that we do NOT want to expose too many implementation details.

So what is the path forward here? Users continue to parse the text of the error messages if they need more detail on what error occured?

2024-08-01 12:03 UTC, crepererum commented
> Someone (who?) creates a more detailed error categorization?

This, by whoever steps up and does the work.

2024-08-04 22:09 UTC, kyle-mccarthy commented
Closing this in favor of #6194.

2024-08-04 22:09 UTC, closed without merging