feat(object_store): add support for server-side encryption with customer-provided keys (SSE-C)
apache/arrow-rs pull request #6230
Opened 2024-08-12 23:52 UTC by jiachengdb

# Which issue does this PR close?

Closes https://github.com/apache/arrow-rs/issues/6229.

# Rationale for this change
 

SSE-C related headers must be set on the S3 API calls.

# What changes are included in this PR?

Propagate SSE-C related encryption headers to S3 API calls.

# Are there any user-facing changes?

Users can enable SSE-C encryption via the following options.

- `aws_server_side_encryption=sse-c`
- `aws_sse_customer_key_base64=...`

2024-08-13 16:02 UTC, tustvold commented on object_store/src/aws/builder.rs
> +    pub fn header_map(&self) -> &HeaderMap {
What is the purpose of this?

2024-08-13 16:06 UTC, tustvold reviewed
I think this will need some tests, I'm not sure if localstack supports server side encryption, but if it does I think this would be my preference. This would help to ensure everything has been hooked up correctly, all the necessary requests decorated, etc...

2024-08-13 16:12 UTC, Xuanwo commented
> I'm not sure if localstack supports server side encryption

FYI: I know `minio` supports `SSE-C`.

2024-08-13 16:23 UTC, wjones127 reviewed
Could you add SSE-C cases to this test: https://github.com/wjones127/arrow-rs/blob/0cc547c21abd7805d995ba3a1aa71d418984e5f1/object_store/src/aws/mod.rs#L522

And then test that against S3 and localstack? You should add any special testing instructions here: https://github.com/wjones127/arrow-rs/blob/0cc547c21abd7805d995ba3a1aa71d418984e5f1/object_store/CONTRIBUTING.md?plain=1#L78

For reference, you can see my original changes when I added the other encryption methods here: https://github.com/apache/arrow-rs/pull/5402

2024-08-13 16:40 UTC, jiachengdb commented
I tried to add the sse-c test like https://github.com/wjones127/arrow-rs/blob/0cc547c21abd7805d995ba3a1aa71d418984e5f1/object_store/src/aws/mod.rs#L522.

But it seems that localstack just ignores the sse-c settings. So I set the sse-c encryption headers, but when I get the object back, it's still shows sse-s3 encryption.

Any suggestions?

2024-08-13 16:42 UTC, jiachengdb commented on object_store/src/aws/builder.rs
> +    pub fn header_map(&self) -> &HeaderMap {
I use it in various places to check `contains_key()` on the HeaderMap.

See:
https://github.com/apache/arrow-rs/pull/6230/files#diff-0feb099a0931110c214fa9b9c8c5528512f38ebf22448772a815baee5973b8c4R610

2024-08-13 16:43 UTC, wjones127 commented
> I tested it on real buckets and it works.

> Any suggestions?

Then create a separate test, and leave instructions for how to test against S3. It's important that others are able to run the same tests and validate.

2024-08-13 16:49 UTC, jiachengdb commented
> Then create a separate test, and leave instructions for how to test against S3. It's important that others are able to run the same tests and validate.

Thanks. So it's okay if the test is skipped by default and will only run if someone sets the correct environment variable, right?

Let me first test if minio can work. If so, I will add instructions for testing against minio.

If minio cannot work, I will add instructions for testing against real S3.

2024-08-13 17:49 UTC, wjones127 commented
> Thanks. So it's okay if the test is skipped by default and will only run if someone sets the correct environment variable, right?

Yes. There are already some tests that only work against the real object store. (For example, IIRC the multi-part uploads for GCS weren't supported by the test server, so we had to run them against real GCS to test them.). So it is expected that not all tests can be run in CI. But we do try to test them manually when possible. Therefore, we'd like to keep those tests checked in so we can perforn those tests.

Of course, automated tests are preferable. You might consider opening an issue on the `localstack` repo letting them know `SSE-C` doesn't seem to be working.

2024-08-14 15:54 UTC, jiachengdb commented
This is the bug report for localstack to support sse-c: https://github.com/localstack/localstack/issues/11356.

2024-08-14 16:17 UTC, wjones127 commented on object_store/src/aws/builder.rs
> +    pub fn header_map(&self) -> &HeaderMap {
`S3EncryptionHeaders` isn't used anywhere in our APIs, so I think it was an accident we made that public. I think we can safely make that private without it being a true API change.

We should change it's definition to

```rust
pub(super) struct S3EncryptionHeaders(pub HeaderMap);
```

And then within the `object_store::aws` module we'll be able to access with `encryption_headers.0`

2024-08-14 18:16 UTC, jiachengdb commented on object_store/src/aws/builder.rs
> +    pub fn header_map(&self) -> &HeaderMap {
Thanks for the suggestions. Made the changes.

2024-08-14 19:00 UTC, bentsku commented
I've just [opened the PR](https://github.com/localstack/localstack/pull/11358) to implement the SSE-C S3 feature in LocalStack, it should be available fairly soon. Not sure you'll need to use MinIO for this, running the tests against S3 in the meantime might be enough?

2024-08-14 19:09 UTC, bentsku commented on object_store/src/aws/builder.rs
> +    /// Type of encryption to use. If set, must be one of "AES256" (SSE-S3), "aws:kms" (SSE-KMS), "aws:kms:dsse" (DSSE-KMS) or "sse-c".
If you set `ServerSideEncryption` to `sse-c`, AWS S3 will raise an error: `InvalidArgument: The encryption method specified is not supported.`

This makes the lines under invalid against real S3 I believe.

2024-08-14 20:11 UTC, jiachengdb commented
> I've just https://github.com/localstack/localstack/pull/11358 to implement the SSE-C S3 feature in LocalStack, it should be available fairly soon. Not sure you'll need to use MinIO for manual testing, running the tests manually against AWS S3 in the meantime might be enough and safer? LocalStack should do a tagged release (3.7.0) in around 2 weeks if you'd like to use it in CI.

We can switch the test from MinIO to localstack once it's the localstack fix is released. I can take this follow-up.

We would like to get the actual code into the next arrow release soon.

2024-08-15 16:19 UTC, wjones127 requested changes
Have a few final suggested changes, then I think we are good to go.

I was able to verify the test passes against Minio and AWS S3.

2024-08-15 16:19 UTC, wjones127 commented on object_store/src/aws/mod.rs
> +            .with_endpoint("https://localhost:9000")
Instead of hard coding these values in the binary, could we take them from environment variables? That way we can just change the environment variables to point them at an AWS S3 bucket to re-use the test.
```suggestion
        let store = AmazonS3Builder::from_env()
            .with_ssec_encryption(customer_key)
```

2024-08-15 16:19 UTC, wjones127 commented on object_store/CONTRIBUTING.md
> +export AWS_SECRET_ACCESS_KEY=minio123
```suggestion
export AWS_BUCKET_NAME=test-bucket
export AWS_ACCESS_KEY_ID=minio
export AWS_SECRET_ACCESS_KEY=minio123
export AWS_ENDPOINT=https://localhost:9000
```

2024-08-15 16:39 UTC, jiachengdb commented on object_store/src/aws/builder.rs
> +    pub fn with_ssec_encryption(mut self, customer_key_base64: impl Into<String>) -> Self {
Good catch.

My intention is to make this API takes an already base64 encoded key.

The reason is because I checked the AWS SDK examples in
https://docs.aws.amazon.com/AmazonS3/latest/userguide/ServerSideEncryptionCustomerKeys.html, that's what they do for the .NET API.

<img width="880" alt="image" src="https://github.com/user-attachments/assets/7f30a07a-6ed2-4ef9-8b2c-a5f2e9db5037">

So now I removed the base64 encoding inside this method, and changed the test to encode first.

2024-08-15 16:40 UTC, jiachengdb commented on object_store/src/aws/builder.rs
> +        }
I added the `if` mainly following other examples in this file like `with_dsse_kms_encryption`.

I've now removed the `if`. Still not sure why the other places need the `if` though.

2024-08-15 16:40 UTC, jiachengdb commented on object_store/src/aws/builder.rs
> +    /// Use SSE-C for server side encryption.
Added a comment

2024-08-15 16:57 UTC, wjones127 approved these changes
Excellent. Thank you!

2024-08-15 20:30 UTC, merged

2024-08-15 21:35 UTC, jiachengdb commented
Hi, I sent a follow up https://github.com/apache/arrow-rs/pull/6260 to make this change safer.

2024-10-09 03:24 UTC, nikhilsinhaparseable commented
Hi, when is the release of object_store planned with `SSE-C encryption`